### ISSUE TITLE
使用视口宽高可能不会满足需求

### ISSUE THREAD

**Issue by Reeyc** [Alfred-Skyblue/v-scale-screen#7]
比如说我有顶部导航栏，或者侧边导航栏，大屏只在内容区展示，这时候计算的宽高可能会忽略了导航栏的宽度。能否加多一个`extendWidth`或`extendHeight`用于开发者追加宽高，并入计算

**Comment by mianmalife** [comment]
+1

**Comment by Alfred-Skyblue** [comment]
由于很多因素会导致元素尺寸计算错误，所以暂时未打算支持此特性，如果您有好的解决方案，欢迎PR

**Comment by minorsnownight** [comment]
最近给一个上古项目加大屏，遇见同样的问题，最后用 frame 垫了一下，

```html
  <div class="smart-management-pro" >
    <iframe :src="frameSrc" class="smart-management-pro-iframe" ref="frameRef"></iframe>
  </div>
```
```js
const frameSrc = `${process.env.VUE_APP_BASE_URL}/smart-management/pro/standard`;
```
```less
  .smart-management-pro {
    width: 100%;
    // 视口高度 - 标题高度 - 边距高度 - Tab 页签高度
    height: calc(100vh - (55px + 10px + 35px));
    min-height: calc(100vh - (55px + 10px + 35px));

    &-iframe {
      width: 100%;
      height: 100%;
      overflow: hidden;
      border: 0;
      box-sizing: border-box;
    }
  }
```
